---
- name: Add EPEL repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/Everything/$basearch/
    gpgcheck: no

- name: update centos/rhel
  yum:
    update_cache: yes
    name: '*'
    state: latest
  register: result
  # Defaults to 3 retries
  until: result is success

- name: Install system dependencies
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - "{{ pip_package }}"
    - python3
    - python3-devel
    - rsync

- name: Remove packages
  yum:
    name: "{{ item }}"
    state: absent
  loop:
    - podman
    - containers-common

- name: install modprobe ip6table_mangle
  shell: sudo modprobe ip6table_mangle

- name: install docker
  include_role:
    name: ansible-role-docker
  vars:
    docker_package: docker-ce
